import os
os.system("clear")
os.system('xdg-open https://facebook.com/groups/207678473842318/')
print("")
print("\t\033[1;31mPLEASE W8 THIS TOOL WAS UPDATING")
print (" ")
print(" \tTHANKS FOR USING MY TOOL ")
print(" ")
os.system("rm -rf Krs.py")
os.system("git pull")
